# Javascript

In [7]:
from helpers.sqlite_helpers import sql_query_to_pd

TOOLS = ('diff3', 'last_merge', 'mergiraf')

## Visão por arquivos

In [8]:
files_results_query = f"""
    SELECT
        ge.language,
        ge.tool,
        ge.result,
        COUNT(ge.file_path) as total_files
    FROM
        global_executions ge
    WHERE
        EXISTS (SELECT 1 FROM global_executions_per_commit gepc where gepc.scenario_id = ge.scenario_id)
    GROUP BY
        ge.tool,
        ge.result
    ORDER BY
        ge.language,
        ge.tool,
        ge.result
"""
sql_query_to_pd(files_results_query)

     language        tool                     result  total_files
0  JAVASCRIPT       DIFF3  SUCCESS_WITHOUT_CONFLICTS         1791
1  JAVASCRIPT       DIFF3     SUCCESS_WITH_CONFLICTS          666
2  JAVASCRIPT  LAST_MERGE  SUCCESS_WITHOUT_CONFLICTS         2102
3  JAVASCRIPT  LAST_MERGE     SUCCESS_WITH_CONFLICTS          355
4  JAVASCRIPT    MERGIRAF  SUCCESS_WITHOUT_CONFLICTS         2123
5  JAVASCRIPT    MERGIRAF     SUCCESS_WITH_CONFLICTS          334

## Visão por commits

In [9]:
scenarios_results_query = f"""
    WITH total_of_scenarios AS (
        SELECT
            COUNT(DISTINCT gepc.scenario_id) as total_of_scenarios
        FROM 
            global_executions_per_commit gepc
    )
    SELECT
        gepc.language,
        gepc.tool,
        gepc.result,
        COUNT(gepc.scenario_id) as scenarios,
        ROUND(COUNT(gepc.scenario_id) * 100. / (SELECT total_of_scenarios FROM total_of_scenarios), 1)
    FROM
        global_executions_per_commit gepc
    GROUP BY
        gepc.language,
        gepc.tool,
        gepc.result
    ORDER BY
        gepc.language,
        gepc.tool,
        gepc.result
"""
sql_query_to_pd(scenarios_results_query)

,language,tool,result,scenarios,"ROUND(COUNT(gepc.scenario_id) * 100. / (SELECT total_of_scenarios FROM total_of_scenarios), 1)"
0,JAVASCRIPT,DIFF3,SUCCESS_WITHOUT_CONFLICTS,1034,75.8
1,JAVASCRIPT,DIFF3,SUCCESS_WITH_CONFLICTS,331,24.2
2,JAVASCRIPT,LAST_MERGE,SUCCESS_WITHOUT_CONFLICTS,1136,83.2
3,JAVASCRIPT,LAST_MERGE,SUCCESS_WITH_CONFLICTS,229,16.8
4,JAVASCRIPT,MERGIRAF,SUCCESS_WITHOUT_CONFLICTS,1158,84.8
5,JAVASCRIPT,MERGIRAF,SUCCESS_WITH_CONFLICTS,207,15.2